### ISSUE TITLE
[meta] Configuration formats

### ISSUE THREAD

**Issue by kvark** [kvark/vange-rs#11]
There is quite a few different formats here to parse:
  - [ ] "uniVang-ParametersFile_Ver_1" (PRM). Contains structured data: arrays and tables. Not very convenient to decode systematically, but relatively easy to do manually.
  - [ ] regular PRM. Contains a number of key: value pairs, should be easy to map (#2).
  - [ ] Lists (LST). Contains a number of different sections, each having a homogeneous array of data. Should be possible to parse.

One way to approach it would be to implement `Decoder` trait for the new parsers and then reflect to structs using `#[derive(RustcDecodable)]`.

**Comment by kvark** [comment]
I figured that manual parsing is the way to go, for these reasons:
  - original names are often SnakeCased, which would unnecessary pollute the code base
  - original names often contain grammar mistakes
  - manual way is universal and straightforward, thanks to a helper class

All kinds of configuration formats are now parsed, even if partially. Closing.
