### ISSUE TITLE
[meta] Voxel ray tracing plan

### ISSUE THREAD

**Issue by kvark** [kvark/vange-rs#221]
- [x] land the implementation - #218
- [ ] create tools to measure GPU time, to start optimization
- [ ] use Morton codes for the terrain buffer. This will improve data locality access patterns. Possibly, use a 2x2 texel tile as the basis (instead of the 2x1 that we have today). Probably need to update it in a compute shader.
- [ ] store voxel data into a buffer as well. Use Morton codes for addressing. Pack bits into 32bit words.
- [ ] describe the rendering approach in the blog.

**Comment by kvark** [comment]
Baseline on my Mac - the default camera of the Level binary on Fostral, default window size.
40ms for RT. Texture units are busy 98.7% of the time.

**Comment by kvark** [comment]
WIth #223 I'm seeing the time for RT raising to 48ms (about 20% hike). Still worth it given the reduced VRAM, and now we are mostly ALU bound, which scales better with GPUs.
